### ISSUE TITLE
build script fails on Debian Jessie

### ISSUE THREAD

**Issue by mikegogulski** [samrushing/irken-compiler#20]
platform info at the end.

```
syadasti@raspberrypi ~/irken-compiler $ python util/bootstrap.py 
protecting bootstrap compiler
cp self/compile.c self/compile.backup.c
cp: cannot stat ‘self/compile.c’: No such file or directory
compiling stage0 binary:
clang -std=c99 -O3 -fomit-frame-pointer -I./include self/compile.c -o self/compile
clang: error: no such file or directory: 'self/compile.c'
clang: error: no input files
compiling stage1 binary:
self/compile self/compile.scm
sh: 1: self/compile: not found
mv self/compile.c self/compile.1.c
mv: cannot stat ‘self/compile.c’: No such file or directory
compiling stage2 binary:
self/compile self/compile.scm
sh: 1: self/compile: not found
mv self/compile.c self/compile.2.c
mv: cannot stat ‘self/compile.c’: No such file or directory
Traceback (most recent call last):
  File "util/bootstrap.py", line 89, in <module>
    samesame = diff ('self/compile.1.c', 'self/compile.2.c')
  File "util/bootstrap.py", line 76, in diff
    if os.stat(p0).st_size == os.stat(p1).st_size:
OSError: [Errno 2] No such file or directory: 'self/compile.1.c'
syadasti@raspberrypi ~/irken-compiler $ !CC
CC=gcc python util/bootstrap.py 
protecting bootstrap compiler
cp self/compile.c self/compile.backup.c
cp: cannot stat ‘self/compile.c’: No such file or directory
compiling stage0 binary:
gcc -std=c99 -O3 -fomit-frame-pointer -I./include self/compile.c -o self/compile
gcc: error: self/compile.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
compiling stage1 binary:
self/compile self/compile.scm
sh: 1: self/compile: not found
mv self/compile.c self/compile.1.c
mv: cannot stat ‘self/compile.c’: No such file or directory
compiling stage2 binary:
self/compile self/compile.scm
sh: 1: self/compile: not found
mv self/compile.c self/compile.2.c
mv: cannot stat ‘self/compile.c’: No such file or directory
Traceback (most recent call last):
  File "util/bootstrap.py", line 89, in <module>
    samesame = diff ('self/compile.1.c', 'self/compile.2.c')
  File "util/bootstrap.py", line 76, in diff
    if os.stat(p0).st_size == os.stat(p1).st_size:
OSError: [Errno 2] No such file or directory: 'self/compile.1.c'
syadasti@raspberrypi ~/irken-compiler $ uname -a
Linux raspberrypi 4.1.7+ #817 PREEMPT Sat Sep 19 15:25:36 BST 2015 armv6l GNU/Linux
syadasti@raspberrypi ~/irken-compiler $ cat /etc/debian_version 
8.0
syadasti@raspberrypi ~/irken-compiler $ gcc --version
gcc (Raspbian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

syadasti@raspberrypi ~/irken-compiler $ clang --version
Raspbian clang version 3.5.0-10+rpi1 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: arm-unknown-linux-gnueabihf
Thread model: posix
```

**Comment by mikegogulski** [comment]
Issue applies to master, not to typewalk.

**Comment by mikegogulski** [comment]
eh, similar stuff here actually

**Comment by samrushing** [comment]
Not sure how the bootstrap compiler went missing?  You need self/compile.c (a pre-compiled compiler) in order to bootstrap.

If you'd like to have another whack at it, try this commit: https://github.com/samrushing/irken-compiler/commit/b67caabecde3505596a25d32974ea02cb33b7d6c

All current work is on the norecursivetypes branch, which will probably be merged to master and tagged soon.

**Comment by samrushing** [comment]
Closing this.  The bootstrap compiler is now stored as `self/bootstrap.scm`.
