### ISSUE TITLE
Cannot bootstrap

### ISSUE THREAD

**Issue by snooper3012** [samrushing/irken-compiler#87]
```
$ CC=gcc make bootstrap
python util/bootstrap.py
copying the bootstrap compiler
cp self/bootstrap.byc self/compile.byc
building VM
gcc vm/irkvm.c -o vm/irkvm -std=c99 -O3 -fomit-frame-pointer -I./include -lffi -D_GNU_SOURCE -ldl
generating posix FFI...
IRKENLIB=. vm/irkvm ffi/gen/genffi.byc -gen ffi/posix.ffi
genc1... FFI = "ffi/posix.ffi"
CC: gcc -E ffi/posix_iface1.c > ffi/posix_iface1.cpp
CC: gcc -dM -E ffi/posix_iface1.c > ffi/posix_iface1.dm
processing 'ffi/posix_iface1.cpp' ...
[gc...collected 194154 words]
[gc...collected 187030 words]
[gc...collected 214734 words]
[gc...collected 196272 words]
[gc...collected 201236 words]
[gc...collected 237561 words]
[gc...collected 788519 words]
[gc...collected 204682 words]
[gc...collected 201211 words]
[gc...collected 207807 words]
[gc...collected 207648 words]
[gc...collected 226015 words]
[gc...collected 227978 words]
[gc...collected 209532 words]
[gc...collected 210692 words]
[gc...collected 214402 words]
[gc...collected 313244 words]
[gc...collected 213695 words]
[gc...collected 222772 words]
[gc...collected 217808 words]
[gc...collected 211614 words]
[gc...collected 224720 words]
[gc...collected 229755 words]
[gc...collected 310817 words]
...done.

uncaught exception 
***
Runtime Error, halting: {u27 "gen-sigs: no such function/object" localtime}
Traceback (most recent call last):
  File "util/bootstrap.py", line 83, in <module>
    system ('IRKENLIB=. vm/irkvm ffi/gen/genffi.byc -gen ffi/posix.ffi')
  File "util/bootstrap.py", line 36, in system
    raise CommandFailed (cmd)
__main__.CommandFailed: IRKENLIB=. vm/irkvm ffi/gen/genffi.byc -gen ffi/posix.ffi
make: *** [Makefile:7: bootstrap] Fehler 1
```

**Comment by samrushing** [comment]
Sorry for the late reply!  looks like the scanner had trouble finding a prototype for `localtime`?  Which platform is this?
